### ISSUE TITLE
Longueur et symboles du code configurables

### ISSUE THREAD

**Issue by vincego** [RedFroggy/keycloak-verify-email-by-code#2]
Nous aimerions pour notre projet utiliser un code de vérification d'email sur 6 caractères de type numérique, en remplaçant par exemple `String code = RandomString.randomCode(8);` par `String code = new RandomString(6, new SecureRandom(), RandomString.digits).nextString();`

Est-il possible de rendre configurables la longueur et le type de caractères utilisés ?

**Comment by dajay** [comment]
Après un refacto, ça semble envisageable au niveau de la configuration du serveur keycloak (standalone.xml).
Cette configuration s'applique à l'ensemble des realms du serveur keycloak.

exemple 

```
<spi name="required-action">
    <provider name="VERIFY_EMAIL_CODE" enabled="true">
        <properties>
            <property name="codeLenght" value="6"/>
            <property name="codeSymbols" value="0123456789"/>
        </properties>
    </provider>
</spi>
```

voir https://www.keycloak.org/docs/latest/server_development/#_implementing_spi

**Comment by vincego** [comment]
Résolu suite à l'intégration de la PR #3, version 11.1 testée avec succès
