### ISSUE TITLE
Does is need to add code changes?

### ISSUE THREAD

**Issue by AAliaksandr** [RedFroggy/keycloak-verify-email-by-code#6]
Hey, we want to use the plugin for our application. I've already installed and configured it, but when I call 'verify-email' api, I get email without code, only with verification link.
Does it need to add any additional changes in the code? If yes, could you pls help in understanding what needs to be added?
Thank you!

**Comment by dajay** [comment]
Hello @AAliaksandr ,
if you use the api endpoint PUT /{realm}/users/{id}/send-verify-email, only VERIF_EMAIL can be executed. See https://github.com/keycloak/keycloak/blob/2fd5a1f4fcaf2ee89be2eadbc12e314d2019cb32/services/src/main/java/org/keycloak/services/resources/admin/UserResource.java#L861.

Try execute-actions-email endpoint.
